updates

diff --git a/Dockerfile-H2-openseesmp-temp b/Dockerfile-H2-openseesmp-temp
--- a/Dockerfile-H2-openseesmp-temp
+++ b/Dockerfile-H2-openseesmp-temp
@@ -106,7 +106,6 @@ RUN . /opt/intel/oneapi/setvars.sh  ; cd /tmp ; git clone https://github.com/cfw
     && cd /tmp ; rm -rf mumps*  
 
 COPY ./openseesmp-makeopensees-2.4.4 /tmp/openseesmp-makeopenseesmp
-ENV  CPATH=/usr/include/tcl8.5:CPATH
 RUN . /opt/intel/oneapi/setvars.sh  ; cd /tmp ; git clone https://github.com/OpenSees/OpenSees \
     && cd OpenSees ; git checkout v2.4.4 \
     && mkdir -pv /tmp/OpenSees/lib \
@@ -118,23 +117,45 @@ RUN . /opt/intel/oneapi/setvars.sh  ; cd /tmp ; git clone https://github.com/Ope
     && cp -r lib /apps/openseesmp \
     && cd /tmp ; rm -rf OpenSees*
 
-#RUN . /opt/intel/oneapi/setvars.sh  ; cd /tmp ; git clone https://github.com/OpenSees/OpenSees \
-#    && cd OpenSees ; git checkout v2.4.4 \
-#    && mkdir -pv /tmp/OpenSees/lib \
-#    && mkdir -pv /tmp/OpenSees/bin \
-#    && mkdir -pv /apps/openseessp \
-#    && cp /tmp/openseesmp-makeopenseesmp ./Makefile.def \
-#    && sed -i 's/OpenSeesMP/OpenSeesSP/g' Makefile.def \
-#    && sed -i 's/D_PARALLEL_INTERPRETERS/D_PARALLEL_PROCESSING/g' Makefile.def \
-#    && sed -i 's/PARALLEL_INTERPRETERS/PARALLEL/g' Makefile.def \
-#    && make \
-#    && cp -r bin /apps/openseessp \
-#    && cp -r lib /apps/openseessp \
-#    && cd /tmp ; rm -rf OpenSees*
+RUN . /opt/intel/oneapi/setvars.sh  ; cd /tmp ; git clone https://github.com/OpenSees/OpenSees \
+    && cd OpenSees ; git checkout v2.4.4 \
+    && mkdir -pv /tmp/OpenSees/lib \
+    && mkdir -pv /tmp/OpenSees/bin \
+    && mkdir -pv /apps/openseessp \
+    && cp /tmp/openseesmp-makeopenseesmp ./Makefile.def \
+    && sed -i 's/OpenSeesMP/OpenSeesSP/g' Makefile.def \
+    && sed -i 's/D_PARALLEL_INTERPRETERS/D_PARALLEL_PROCESSING/g' Makefile.def \
+    && sed -i 's/PARALLEL_INTERPRETERS/PARALLEL/g' Makefile.def \
+    && make \
+    && cp -r bin /apps/openseessp \
+    && cp -r lib /apps/openseessp \
+    && cd /tmp ; rm -rf OpenSees*
 
 
 
 #
+
+
+FROM ubuntu:18.04 as buildtemp2
+
+RUN mkdir -p /opt/build && mkdir -p /opt/dist
+RUN apt-get update && apt-get upgrade -y && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    ca-certificates curl && \
+  rm -rf /var/lib/apt/lists/*
+
+# install cmake
+RUN cd /opt/build && \
+    curl -LO https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-linux-x86_64.sh && \
+    mkdir -p /opt/dist//usr/local && \
+    /bin/bash cmake-3.24.3-linux-x86_64.sh --prefix=/opt/dist//usr/local --skip-license
+
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM ubuntu:18.04
 RUN apt-get update && apt-get upgrade -y && \
@@ -158,14 +179,14 @@ RUN apt-get update && apt-get upgrade -y && \
     ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git intel-oneapi-runtime-ccl intel-oneapi-runtime-compilers intel-oneapi-runtime-dal intel-oneapi-runtime-dnnl intel-oneapi-runtime-dpcpp-cpp intel-oneapi-runtime-dpcpp-library intel-oneapi-runtime-fortran intel-oneapi-runtime-ipp intel-oneapi-runtime-ipp-crypto intel-oneapi-runtime-libs intel-oneapi-runtime-mkl intel-oneapi-runtime-mpi intel-oneapi-runtime-opencl intel-oneapi-runtime-openmp intel-oneapi-runtime-tbb intel-oneapi-runtime-vpl intel-opencl intel-level-zero-gpu level-zero level-zero-devel  && \
   rm -rf /var/lib/apt/lists/*
 
-COPY --from=build /opt/dist /
+COPY --from=buildtemp2 /opt/dist /
 
 ENV LANG=C.UTF-8
 ENV LD_LIBRARY_PATH=/opt/intel/oneapi/lib
 
 RUN apt-get update  \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    vim less python-dev python3-pip libhdf5-dev git libmysqlclient-dev tcl8.5-dev make gcc-multilib tk8.5-dev flex bison libbz2-dev zlib1g
+    vim less python-dev python3-pip libhdf5-dev git libmysqlclient-dev tcl8.5-dev make gcc-multilib tk8.5-dev flex bison libbz2-dev zlib1g 
 RUN mkdir -p /opt/build && mkdir -p /opt/dist
 RUN apt-get update && apt-get upgrade -y && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
